CREATE DATABASE IF NOT EXISTS hos;
GRANT ALL PRIVILEGES ON hos.* TO pc@localhost IDENTIFIED BY 'pc';

USE hos;

CREATE TABLE IF NOT EXISTS category (
	id INT(4)  UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20)
) engine=InnoDB;
